title: "Predicción de Churn — Telco"
author: "Sergio Cadavid · Juan Conrado · Mateo Chang"
logo: ""

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath

html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: true

latex:
  latex_documents:
    targetname: telco_churn.tex

sphinx:
  config:
    html_show_copyright: false
    language: es
